// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFSCELRmK8AFz8oTUcdYrqnDwpnK-VrQs',
    appId: '1:927831368807:web:34f56f9baeb00b1dff60c2',
    messagingSenderId: '927831368807',
    projectId: 'my-note-project-78e2c',
    authDomain: 'my-note-project-78e2c.firebaseapp.com',
    storageBucket: 'my-note-project-78e2c.appspot.com',
    measurementId: 'G-87MQ3S33FH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzbPX-R-2FgCkmv_iYtItrQNUmsFPpEl8',
    appId: '1:927831368807:android:bde330aed05301c8ff60c2',
    messagingSenderId: '927831368807',
    projectId: 'my-note-project-78e2c',
    storageBucket: 'my-note-project-78e2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUNetQmMkZq0HzNXg-e9hvPYrU-KXps5g',
    appId: '1:927831368807:ios:764bcc6216d3189fff60c2',
    messagingSenderId: '927831368807',
    projectId: 'my-note-project-78e2c',
    storageBucket: 'my-note-project-78e2c.appspot.com',
    iosClientId:
        '927831368807-durt8ir416hh5t2e6f6ka60megnd9tkh.apps.googleusercontent.com',
    iosBundleId: 'com.mbtechnologies.mypersonalnote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUNetQmMkZq0HzNXg-e9hvPYrU-KXps5g',
    appId: '1:927831368807:ios:764bcc6216d3189fff60c2',
    messagingSenderId: '927831368807',
    projectId: 'my-note-project-78e2c',
    storageBucket: 'my-note-project-78e2c.appspot.com',
    iosClientId:
        '927831368807-durt8ir416hh5t2e6f6ka60megnd9tkh.apps.googleusercontent.com',
    iosBundleId: 'com.mbtechnologies.mypersonalnote',
  );
}
